#!/usr/bin/env python

from optparse import OptionParser
import logging
from WmDisplay import WmDisplay

def main():

    opt_parser = OptionParser(usage="usage: %prog [options]")

    opt_parser.add_option('', '--display',
                          action="store", type="string", dest="display",
                          default=":0", help="Display to run window manager on")

    opt_parser.add_option('-d', '--debug',
                          action='store_true', dest='debug',
                          help="Print debug output")

    (options, dummy) = opt_parser.parse_args()

    if options.debug:
        log_level = logging.DEBUG
    else:
        log_level = logging.INFO
    logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', datefmt='%Y-%m-%d %H:%M:%S', level=log_level)

    display = WmDisplay(options.display)
    display.run_event_loop()

################################################################################

if __name__ == '__main__':
    main()
